---
application: crr
repository: ssh://git@stash.nubic.northwestern.edu:7999/crr/crr.git
deployer: crr-runner
development:
  server_name: crr.dev
staging:
  app_host: vtfsmnubicapps01.fsm.northwestern.edu
  server_name: crr-dev.nubic.northwestern.edu
  server_alias: crr-dev.nubic.northwestern.edu
production:
  app_host: vfsmnubicapps01.fsm.northwestern.edu
  server_name: crr.nubic.northwestern.edu
  server_alias: crr.nubic.northwestern.edu

